---
- name: 'Show variable dns_server for web_servers'
  hosts: web_servers
  tasks: 
    - name: show name of web_servers
      debug:
        msg:
          - '{{ inventory_hostname }}'
    
    - name: show dns_server variable for web_servers
      debug:
        var: dns_server

- name: 'Show dns_server value from target02 avaible for all web_servers'
  hosts: web_servers
  tasks: 
    - name: show dns server of target02 accessible on each host
      debug:
        msg:
          - '{{ inventory_hostname }}'
          - ' {{ hostvars["target02"].dns_server }}' 
