---
- name: 'Show Variable Scope dns_server is defined only for target02'
  hosts: web_servers
  tasks: 
    - name: show dns_serveur ip
      debug:
        var: dns_server
    - name: show all
      debug:
        var: hostvars
