---
- name: Start default nginx service
  hosts: web_servers
  become: yes
  tasks:
    - name: Allow Nginx to bind to port 80 in SELinux
      command: semanage port -a -t http_port_t -p tcp 80
      ignore_errors: yes  

    - name: Ensure Nginx is installed
      **************

    - name: Start and enable Nginx service
      *************
