---
- name: Read and dispplay /etc/hosts
  hosts: web_servers
  gather_facts: false
  tasks:
    - name: Read the /etc/hosts file
      command: cat /etc/hosts
      **********************

    - name: Display file content
      debug:
        msg: "{{ ************** }}"

