---
- name: Use_loop
  hosts: web_servers
  gather_facts: false
  vars:
    packages:
      - name: nginx
        required: True
      - name: mysql
        required: True
      - name: apache
        required: False

  tasks:
    - name: Show packages name if required
      debug:
        var: item.name
      when: '{{ item.required }} == True'
      loop: '{{ packages }}'
