---
- name: Show Ansible variable definied for web_servers
  hosts: web_servers
  tasks: 
    - name: Show variables on web_servers
      debug:
        var: variable_web_servers

- name: Show Ansible variable definied for local_server
  hosts: local_server
  tasks: 
    - name: Show variables on local_server
      debug:
        var: variable_local_server

- name: Show Ansible variable definied for all_servers
  hosts: all_servers
  tasks: 
    - name: Show variables on all_servers
      debug:
        var: variable_all_servers

- name: Show Ansible variable definied for target01
  hosts: target01
  tasks: 
    - name: Show variables on target01
      debug:
        var: variable_target01

         

          

