---
- name: Show success + changed
  hosts: web_servers
  gather_facts: no
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: test httpd
      command: httpd
      register: result
    - name: display result
      debug:
        var: result.stdout

    - name: desinstall httpd
      yum:
        name: httpd
        state: absent
    - name: test desinstallation
      ignore_errors: yes
      command: htttpd
